# Generated by Django 6.0.4 on 2026-05-20 22:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upc', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(default='each', max_length=50)),
                ('case_pack', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.business')),
            ],
            options={
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('import_type', models.CharField(choices=[('sales', 'Sales'), ('purchases', 'Purchases'), ('pricebook', 'Pricebook'), ('inventory', 'Inventory'), ('other', 'Other')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('total_rows', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='core.location')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PricebookItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricebook_items', to='core.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricebook', to='core.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricebook_items', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('counted_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('variance', models.DecimalField(decimal_places=3, editable=False, max_digits=10)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.CharField(blank=True, max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_snapshots', to='core.location')),
                ('pricebook_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='core.pricebookitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_ref', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('partial', 'Partially Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('ordered_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_ordered', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricebook_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='core.pricebookitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='core.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='RawImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.importbatch')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sold_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('square', 'Square POS'), ('clover', 'Clover POS'), ('manual', 'Manual Entry')], default='csv', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.location')),
            ],
            options={
                'ordering': ['-sold_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upc_raw', models.CharField(blank=True, max_length=50)),
                ('product_name_raw', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pricebook_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='core.pricebookitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lines', to='core.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.saletransaction')),
            ],
        ),
        migrations.CreateModel(
            name='ShrinkageAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('variance', models.DecimalField(decimal_places=3, max_digits=10)),
                ('confidence_score', models.FloatField(default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrinkage_alerts', to='core.location')),
                ('pricebook_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shrinkage_alerts', to='core.pricebookitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shrinkage_alerts', to='core.product')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inventorysnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rep_name', models.CharField(blank=True, max_length=255)),
                ('rep_phone', models.CharField(blank=True, max_length=20)),
                ('rep_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='core.business')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='pricebookitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricebook_items', to='core.supplier'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['location', 'uploaded_at'], name='core_import_locatio_650cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['import_type', 'status'], name='core_import_import__944898_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['location', 'product', 'counted_at'], name='core_invent_locatio_a19b49_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorysnapshot',
            index=models.Index(fields=['pricebook_item', 'counted_at'], name='core_invent_pricebo_cc8f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='rawimportrow',
            index=models.Index(fields=['batch'], name='core_rawimp_batch_i_7afa16_idx'),
        ),
        migrations.AddIndex(
            model_name='rawimportrow',
            index=models.Index(fields=['status'], name='core_rawimp_status_27d624_idx'),
        ),
        migrations.AddIndex(
            model_name='rawimportrow',
            index=models.Index(fields=['is_mapped'], name='core_rawimp_is_mapp_750989_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawimportrow',
            unique_together={('batch', 'row_number')},
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['location', 'sold_at'], name='core_saletr_locatio_9e2a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='saletransaction',
            index=models.Index(fields=['transaction_ref'], name='core_saletr_transac_36975c_idx'),
        ),
        migrations.AddIndex(
            model_name='salelineitem',
            index=models.Index(fields=['product'], name='core_saleli_product_0c30b3_idx'),
        ),
        migrations.AddIndex(
            model_name='salelineitem',
            index=models.Index(fields=['pricebook_item'], name='core_saleli_pricebo_f8cc7c_idx'),
        ),
        migrations.AddIndex(
            model_name='salelineitem',
            index=models.Index(fields=['upc_raw'], name='core_saleli_upc_raw_353bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='shrinkagealert',
            index=models.Index(fields=['location', 'created_at'], name='core_shrink_locatio_b0e994_idx'),
        ),
        migrations.AddIndex(
            model_name='shrinkagealert',
            index=models.Index(fields=['product', 'created_at'], name='core_shrink_product_68cfe7_idx'),
        ),
        migrations.AddIndex(
            model_name='shrinkagealert',
            index=models.Index(fields=['severity', 'is_resolved'], name='core_shrink_severit_570b95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('business', 'name')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['location', 'ordered_at'], name='core_purcha_locatio_d46f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_ref'], name='core_purcha_order_r_6adde5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricebookitem',
            unique_together={('location', 'product')},
        ),
    ]
